### PR TITLE
In semantics.json set media default to none

### PR DESCRIPTION
**Pull request by rezeau**

### CODE REVIEW

**Comment by otacke** [comment]
@rezeau I don't know whether setting the image as default was done on purpose in order to encourage adding something here instead of having a blank slide. Maybe @janlindso knows. From my perspective, starting blank would indeed make sense, but see above.

**Comment by janlindso** [comment]
I think it was set to `Image `by default since that would be most used, and it shouldn't make any difference if you select `none` or select `image` without supplying an image.

**Comment by otacke** [comment]
@janlindso Doesn't make a difference in the end, no.

**Comment by rezeau** [comment]
@janlindso When offering a choice of 4 Media types plus None of those, you cannot infer that Image will be selected by most users. Much better to leave the default at None, otherwise, it does make a difference, if the user does not want to select any media and forgets to select None, then a warning message will be displayed...
@otacke It's impossible to display a completely blank slide, as a Description is always necessary. A slide with a Description and no media is perfectly acceptable in Timeline.

**Comment by otacke** [comment]
@rezeau In the _view_, it does not make a difference if you set the value to "none" or if you set it to "Image" but don't use any. That is what @janlindso was referring to.

**Comment by janlindso** [comment]
We will keep this as it, but thanks for your suggestions @rezeau!

**Pull request closed without merging**
