### PR TITLE
Remove the Date.parse() test which does not accept negative dates in …

### PR DESCRIPTION
**Pull request by rezeau**
…timeline.utils.tsx.

Add regular expression tests for dates input in semantics.json.

### CODE REVIEW

**Comment by otacke** [comment]
@rezeau Adding the regular expression is fine (and the regular expression itself is) and a good addition to inform users about malformed date strings, but one should not assume that content is created using the editor only.

Just like when designing a server-side component one should not rely on the requests adhering to some format even if it was checked client-side, there's nothing wrong with checking the string in the code as well.

**Comment by rezeau** [comment]
@otacke "there's nothing wrong with checking the string in the code as well."
1.- That checking is done here in the code: https://github.com/rezeau/h5p-ndla-timeline/commit/eee7ee4c1025e3bebf005136d484d3b3a7f11bca#diff-e4ae6212d93851ddb9f7c370c824ff2c414af890af9ba9f836bdc192de3b608aL22-L26
2.- Anyway, the original reason for this PR was the removal of the Date.parse() check which does not accept negative dates.

**Comment by otacke** [comment]
@rezeau The first checking that you removed is done to prevent illegal values from being set which is part of checking - it will not check the string for validity, no. Try `2015-02-31` in your solution (yes, you cannot set this in the editor, but see comment above). You'll yield `MARCH 3, 2015`.

I could not detect any trouble with negative dates in the original solution (Using Chrome and values such as "-2000", "-2000-10" or "-2000-10-11"). Maybe you could improve your pull request by clearly stating what you want to fix, what configuration you're using and what browser as Date functions tend to be treated differently across browsers? That would help tremendously.

I can see that Firefox is treating `Date.parse` differently and will lead to the removal of dates which is probably what you are referring to - I don't know. This is definitely something that should be fixed, but ideally not by introducing another issues even if that issue is less likely to occur.

**Comment by otacke** [comment]
@rezeau Instead of replacing one bug with another, have you thought about something such as

```
/*
 * Firefox cannot handle negative years in Date.parse unless the argument uses
 * ISO 8601 format with expanded years.
 * @see https://tc39.es/ecma262/#sec-expanded-years
 */
const isDateValid = (dateString: DateString): boolean => {
  const date = parseDateString(dateString);

  const year =
    date.year < 0
      ? `-${(-1 * date.year).toString().padStart(6, "0")}`
      : `+${date.year.toString().padStart(6, "0")}`;
  const month = (date.month ?? 1).toString().padStart(2, "0");
  const day = (date.day ?? 1).toString().padStart(2, "0");

  return !Number.isNaN(Date.parse(`${year}-${month}-${day}T00:00:00Z`));
};
```
for checking if a date set in the editor or in the params directly is valid?

Then `parseDate` could be boiled down to
```
export const parseDate = (dateString: string): TimelineDate | null => {
  if (!isDateString(dateString)) {
    return null;
  }

  if (!isDateValid(dateString)) {
    return null;
  }

  return parseDateString(dateString);
};
```
while making sure the string is well formed and then checking whether the date is valid and not something like April 31.

That should work for negative years on Firefox and other browsers that are not as forgiving as Chrome for instance.

**Pull request merged**
