### PR TITLE
remove useless dates from title slide in semantics.json

### PR DESCRIPTION
**Pull request by rezeau**

### CODE REVIEW

**Comment by rezeau** [comment]
@otacke You're quite right, of course. I have tried to update the languages by using the console command:
h5p update-translations h5p-ndla-timeline
but it just mixes up the language strings instead of simply removing the un-needed strings.
Should I edit the language files one by one and remove those un-needed strings by hand?

**Comment by otacke** [comment]
@rezeau Have you tried looking at the help page of the H5P CLI tool?

Files get mixed up, because you have already removed the fields from semantics.json. The H5P CLI tool has no way of determining what was changed. That's what you need to do.

You can add a property with the key `"state"` and a value of `"new"` to a field that you added or `"updated"` or `"removed"` to a field in `semantics.json` that should be updated or removed. Upon then running the `update-translations` command, the field will be added or updated or removed from semantics.json and the translation files.

**Comment by rezeau** [comment]
@otacke 

- Thanks for the tip, it worked fine; I'll now update my PR with the updated language files.
- I did look at the H5P developer documentation at https://h5p.org/h5p-cli-guide but could not find any reference to the the update-translations command nor at the trick about adding a state field to semantics.json. Maybe I did not look in the right place?

**Comment by rezeau** [comment]
> 🎉 The library version was updated from **** to ****.
What does this cryptic message mean?

**Comment by otacke** [comment]
@rezeau Seems you never entered `h5p` only which would list all the available commands including `help` which could have lead you to `h5p help udate-translations` yielding "Will scan the language folder and update each file according to semantics.json. Set the special field property "state" to one of: new, updated, removed"

The message 
> "The library version was updated from **** to ****."

is generated by the github action that runs when a pull request is created (https://github.com/boyum/comment-h5p-library-version-action). Here doesn't seem to be able to determine version numbers as the pull request does not originate from the target repository.

**Pull request closed without merging**
