### PR TITLE
Checks that end date of event is later than the start date and issues…

### PR DESCRIPTION
**Pull request by rezeau**
… an alert error message if wrong end date.

### CODE REVIEW

**Comment by otacke** [comment]
@rezeau Please make sure to lint your pull requests with the linting scripts defined in `package.json` in order to adhere to the coding style set for this repository. It will hint you to a couple of issues. Also, if you're using a properly configured editor such as Visual Studio, it should hint you to issues in your code directly. You may want to wait though, as this should be updated shortly.

Apart from that:
- Please don't use `alert` for anything. If you want to warn the author, please use `console.warn`. This is opinionated, yes.
- The comparison could be much simpler. If `startDate`/`endDate` is not `null` when you're checking, then the respective `event.startDate`/`event.endDate` must have been valid and you can safely turn these into milliseconds using `Date.parse` and you can determine which is larger directly without all the extra code. Also, your warning message is always the same and you'd only need one condition. If you feel that condition is too large, you can always split it up like
```
const condition1 = ...;
...
const conditionN = ...;

if (condition1 || ... || condition2) {
  // Give out warning
}
```
with proper names for the conditions, of course. If it's more then three, you could also put them all into one `conditions` array in order to use something like `if (condions.some((condition) => condition) { ... }` for an `OR`-clause to check whether some condition is `true` in order to keep the code concise.

**Comment by rezeau** [comment]
@otacke Thanks for your valuable comments.
1.- I'll use npm run eslint:check to check my syntax. Thanks for the tip.
2.- As regards the use of console.error/warn instead of alert(), I am of opinion that it's not obvious that an end-user entering dates in a Timeline content will have their console displayed. Not all end-users are developers, and most of them are not even aware of the existence of their browser console! So I'll stick to displaying an alert() even though it makes eslint unhappy.
3.- You write "_If startDate/endDate is not null when you're checking, then the respective event.startDate/event.endDate must have been valid and you can safely turn these into milliseconds using Date.parse ..._" Unfortunately Date-parse() does not work with negative dates, as reported in my PR #412...
4.- I will look at your suggestion to make my error warning more concise and re-post my modified PR soon.

**Comment by otacke** [comment]
@rezeau

1) I already said that not using `alert` is opinionated, but obviously the person who set up the linter also shared that opinion (eslint will complain). If you change the user interface, it's common practice to pre-qualify the change with the maintainer first. Here you should discuss this with NDLA - and probably implement a proper solution not an ugly `alert` that stops execution.

2) See my comment there.

**Comment by otacke** [comment]
@rezeau Try this for a change.

Replace https://github.com/NDLANO/h5p-ndla-timeline/blob/main/src/utils/timeline.utils.tsx#L164 with

```
const endDate = event.endDate ? parseDate(event.endDate) : null;
```

to make the type a little more concise, and then calling
```
if (!isDateOrderOK(startDate, endDate)) {
  // Do something
}
```

should work if you use something along the lines of

```
const isDateOrderOK = (
  startDate: TimelineDate | null,
  endDate: TimelineDate | null,
): boolean => {
  const start: TimelineDate = Object.create(startDate);
  start.year = start.year ?? -Infinity;
  start.month = start.month ?? -Infinity;
  start.day = start.day ?? -Infinity;

  const end: TimelineDate = Object.create(endDate);
  end.year = end.year ?? -Infinity;
  end.month = end.month ?? -Infinity;
  end.day = end.day ?? -Infinity;

  return !(
    start.year > end.year ||
    (start.year === end.year && start.month > end.month) ||
    (start.year === end.year &&
      start.month === end.month &&
      start.day > end.day)
  );
};
```
as the implementation of `isDateOrderOK`. That is shorter and feels a little cleaner. It could even be cleaned up further, but having a separate function just to create the derived `TimelineDate` objects felt a little like over-engineering.

But `alert` instead of some clean solution... phew. You may be up for yet another of your forks if you want to get your own way again.

**Comment by rezeau** [comment]
@otacke Thanks for your latest suggestions, which I will try out and re-write my PR some time later this week.

**Comment by otacke** [comment]
@rezeau One can mark a pull-request as a draft on the right-hand side under the reviewer suggestions. Did that. When done, one can mark it as "ready for review" underneath the comment section.

**Comment by otacke** [comment]
Please ensure to run `npm lint:fix` on this repository for now to fix formatting and other coding style issues in your code.

**Comment by rezeau** [comment]
@otacke If I run npm lint:fix it changes a lot of the files in my local repository. If I then look at the changes they're all the same and I get this message (for example for script '.eslintrc.json'):
warning: in the working copy of '.eslintrc.json', LF will be replaced by CRLF the next time Git touches it
No idea what this means and what I should do now.

**Comment by otacke** [comment]
@rezeau I didn't configure linting and it will be changed to better reflect the overall H5P style guide anyway, but it should at least fix your coding style violations. Run eslint manually if needed.

**Comment by otacke** [comment]
@janlindso The automated check fails, because the creator of the github action potentially did not have pull requests from external contributors in mind. The "Check H5P library version" action does not seem to be able to take remote branches into account and fails. It passes when run on a branch of this repository. This might need improvement.

**Comment by rezeau** [comment]
@otacke I had not realized that the problem of my PR was with wrong indentation. Thanks for fixing this!

**Comment by otacke** [comment]
@rezeau "fix your coding style violations (wrong indentation)" 😉😁 https://github.com/NDLANO/h5p-ndla-timeline/pull/415#issuecomment-1544661203

**Pull request merged**
