### PR TITLE
Use iframe instead of div

### PR DESCRIPTION
**Pull request by otacke**
When merged in, should fix https://github.com/NDLANO/h5p-ndla-timeline/issues/489

Please fix the Chromatic key or whatever is wrong with the github action if you want to use the Storybook test.

### CODE REVIEW

**Comment by rezeau** [comment]
@otacke Tested your PR, doesn't work for me, iframe height is much too small:
in Drupal 7
<iframe id="h5p-iframe-151" class="h5p-iframe h5p-initialized" data-content-id="151" style="height: 27px;" src="about:blank" frameborder="0" scrolling="no" allowfullscreen="allowfullscreen" allow="geolocation *; microphone *; camera *; midi *; encrypted-media *" title="ndla timeline default 0000"></iframe>

in Lumi
<iframe id="h5p-iframe-4071990560" class="h5p-iframe h5p-initialized" data-content-id="4071990560" style="height: 1px;" src="about:blank" frameborder="0" scrolling="no" title="H5P"></iframe>

This height works for me:
**style="height: 500px;"**

**Comment by otacke** [comment]
I had it running fine on Lumi and on a moodle 4.2 sandbox. Please try again making sure all caches (browser, platform, etc.) are clean.

**Comment by rezeau** [comment]
@otacke 
I'll be away from home until the end of the week...  I'll try again when I'm back and report.

**Comment by otacke** [comment]
As I said, it's working nicely here:

- [Lumi](https://pasteboard.co/VTBsipQ4d3GT.png)
- [moodle 4.2](https://pasteboard.co/Ldu0y8Hjxxzw.png)

It's possible that the database entry for the embed method doesn't get updated when only bumping the patch version (if you're not a dev platform), so I bumped the minor version now.

I guess @janlindso is going to check as well.

**Comment by rezeau** [comment]
@otacke Just tested your latest bump to this PR and I'm pleased to report that it's working OK both on Moodle and Lumi!
Thanks for your prompt and efficient work, as always...

**Comment by rezeau** [comment]
@otacke Sorry, but I have a small bug when using your latest commit... Upon loading an NDLA Timeline content, in navigation, the left column containing the zoom buttons and first/last slide buttons is not displayed. It is only displayed if the content is resized manually, as shown on attached animated gif capture. Looks like some kind of automatic resize is missing when loading the content...
ndla030bug

**Comment by otacke** [comment]
@rezeau No need to be sorry. Should be fixed now, but this is using some workaround now that might be implemented cleaner.

**Comment by rezeau** [comment]
@otacke Works fine now, thanks!

**Pull request merged**
