### PR TITLE
Add caption and credits

### PR DESCRIPTION
**Pull request by rezeau**
Suggested PR to add Caption and Credits fields to the Timeline media field as per the original timeline.knightlab version.  Based on the latest version available h5p ndla timeline (0.1.0).
I maintain that both fields can be really useful, as demonstrated in the original timeline.knightlab Woman in computing example.
The Credits field can contain a link to the external media original source, which is a nice way of acknowledging the use of that source even if, as stated elsewhere by @otacke full copyright info is not needed here.
The Caption field is a common way of displaying e.g. a legend for an image, etc. A very useful feature which by the way should be made available in all H5P contents where a media, especially an image is available.
Both fields are optional, of course. They work fine as H5P content and I see no reason for not adding them to the h5p ndla timeline.
It would be a pity for the h5p ndla timeline to _restrict_ the wealth of the features offered by the original timeline.knightlab.
Of course the final decision rests with the NDLANO team. Thanks!

### CODE REVIEW

**Comment by otacke** [comment]
Not commenting on the functionality here, but you're request falls short for not adding the labels (in English) to all the language files.

**Comment by rezeau** [comment]
@otacke Yes, I'm aware of this problem. Since there are only 3 labels to add and only 7 language files currently in the ndla timeline language dir I can do it "by hand". But this operation is rather tedious and prone to errors.
Do you have a suggestion for automating this kind of operation (and making it safe)?
Thanks!

**Comment by otacke** [comment]
Just because something is tedious to do does not mean it can be neglected in a pull request (or mark the request as work-in-progress/draft at least, so the maintainers and visitors know that it is not done yet).

You can add the property `state` with the value `new` to a field in `semantics.json` and then use the `update-translations` command of the H5P CLI tool.

**Comment by rezeau** [comment]
@otacke Thanks for reminding me to be more careful with my pull requests and thanks for pointing to the `update-translations` command of the H5P CLI tool. I have pushed my new changes to my PR.

On the topic of translation, yesterday I translated the h5p-ndla-timeline language strings into French on https://translate-h5p.tk/weblate/projects/h5p/h5p-ndla-timeline/ Do I need to do anything else now or will my translations be automatically merged into h5p-ndla-timeline?
Thanks!

**Comment by otacke** [comment]
You don't need to bother with pull-requests or related issues at all when using translate-h5p.tk. When someone has time to review the contribution, the pull request will be dealt with.

**Pull request closed without merging**
